export default {
  CREATE: 'CREATE',
  TOGGLE_COMPLETE: 'TOGGLE_COMPLETE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  TOGGLE_ALL: 'TOGGLE_ALL',
  UPDATE_FILTER: 'UPDATE_FILTER',
  CLEAR_COMPLETED: 'CLEAR_COMPLETED'
}
